# Generated by Django 4.0.5 on 2022-06-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receivers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=150)),
                ('completion_date', models.DateField()),
                ('issue_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receivers_app.receiver')),
            ],
        ),
    ]
