# Generated by Django 4.0.5 on 2022-08-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/avatar.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_logo',
            field=models.ImageField(default='images/no_photo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
